import { Geist, Geist_Mono, Onest, Fredoka, Outfit } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const onest = Onest({
  variable: "--font-onest",
  subsets: ['latin'],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
  
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} ${fredoka.variable} ${outfit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
