import { Geist, Geist_Mono, Onest, Fredoka, Outfit } from "next/font/google";
import "./globals.css";

const onest = Onest({
  variable: "--font-onest",
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
});

const outfit = Outfit({
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} ${fredoka.variable} ${outfit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
